### PR TITLE
Add netcore verison of GraphGetStarted.csproj and v-bump Microsoft.Azure.Graphs to 0.3.0-preview

### PR DESCRIPTION
**Pull request by olivertowers**
Adds netcore verison of GraphGetStarted.csproj and v-bump Microsoft.Azure.Graphs to 0.3.0-preview

netcore GraphGetStarted.csproj uses the same Program.cs as netfx version.

### CODE REVIEW

**Comment by olivertowers** [comment]
Please review:
@mimig1  
@arramac

**Comment by mimig1** [comment]
Can you run the project and see if what's in https://docs.microsoft.com/en-us/azure/cosmos-db/create-graph-dotnet still makes sense and is accurate, and make any updates in a separate doc PR?

**Comment by arramac** [comment]
looks good to me.

**Comment by olivertowers** [comment]
@mimig1 - Opened a PR for those changes.

Also, I've changed the original approach for the sample project. Instead of using two separate projects, I've folded the netcore/netfx support into one DotNet 2.0 project which can support multi-targeting.
Feel that this is a cleaner approach, and is follows up-to-date practices for mutli-plat/mutli-targeting projects, and avoids having forked sample code.

**Comment by olivertowers** [comment]
@sivethe 
@LuisBosquez

**Comment by mimig1** [comment]
@olivertowers The sample updates look good to me.

**Comment by scamp81** [comment]
Not sure if this is the place to put this, but I'm trying to reference the new .3.0 graph SDK in a .net core 2.0 project hosted on azure app service and it fails because the Graphs DLL is compiled in 64 bit and Azure App service will only run .net core projects in 32 bit mode.  Any chance for a re-release of the nuget package compiled for any CPU?

https://stackoverflow.com/questions/42726350/how-to-change-azure-app-service-to-64-bit

**Comment by olivertowers** [comment]
@scamp81 - I don't know of a technical reason why we can't switch to AnyCPU. We should be able to get this out in the next package release.

**Comment by scamp81** [comment]
Thanks!

**Comment by olivertowers** [comment]
#sign-off

**Pull request merged**
